# Generated by Django 5.2.17 on 2026-09-06 12:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Associado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matricula",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Matrícula"
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome Completo"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "telefone",
                    models.CharField(max_length=30, verbose_name="Telefone / WhatsApp"),
                ),
                (
                    "cpf",
                    models.CharField(max_length=18, unique=True, verbose_name="CPF"),
                ),
                ("rg", models.CharField(blank=True, max_length=30, verbose_name="RG")),
                (
                    "data_nascimento",
                    models.DateField(verbose_name="Data de Nascimento"),
                ),
                (
                    "tipo_sanguineo",
                    models.CharField(
                        blank=True,
                        default="O+",
                        max_length=10,
                        verbose_name="Tipo Sanguíneo",
                    ),
                ),
                ("data_filiacao", models.DateField(verbose_name="Data de Filiação")),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Sócio Atleta", "Sócio Atleta"),
                            ("Sócio Efetivo", "Sócio Efetivo"),
                            ("Sócio Colaborador", "Sócio Colaborador"),
                            ("Sócio Benemérito", "Sócio Benemérito"),
                        ],
                        default="Sócio Atleta",
                        max_length=50,
                        verbose_name="Categoria de Sócio",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Ativo", "Ativo"),
                            ("Pendente", "Pendente"),
                            ("Inativo", "Inativo"),
                            ("Bloqueado", "Bloqueado"),
                        ],
                        default="Ativo",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="associados/fotos/",
                        verbose_name="Foto 3x4",
                    ),
                ),
                (
                    "foto_url",
                    models.URLField(
                        blank=True,
                        help_text="Caso a foto esteja hospedada externamente",
                        verbose_name="URL da Foto (opcional)",
                    ),
                ),
                (
                    "validade_carteirinha",
                    models.DateField(
                        blank=True, null=True, verbose_name="Validade da Carteirinha"
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        default="São Gonçalo do Amarante",
                        max_length=100,
                        verbose_name="Cidade",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        default="RN", max_length=2, verbose_name="Estado (UF)"
                    ),
                ),
                (
                    "identidade_surda",
                    models.CharField(
                        default="Surdo(a)", max_length=60, verbose_name="Identidade"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Atualizado em"),
                ),
            ],
            options={
                "verbose_name": "Associado",
                "verbose_name_plural": "Associados",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="CapituloEstatuto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(verbose_name="Número do Capítulo"),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Capítulo"),
                ),
                ("ordem", models.PositiveIntegerField(default=1, verbose_name="Ordem")),
            ],
            options={
                "verbose_name": "Capítulo do Estatuto",
                "verbose_name_plural": "Capítulos do Estatuto",
                "ordering": ["ordem"],
            },
        ),
        migrations.CreateModel(
            name="Evento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Evento"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, unique=True, verbose_name="Slug / URL"
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        default="Esportivo e Cultural",
                        max_length=60,
                        verbose_name="Tipo do Evento",
                    ),
                ),
                (
                    "data_inicio",
                    models.DateTimeField(verbose_name="Data e Horário de Início"),
                ),
                (
                    "data_fim",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data e Horário de Término"
                    ),
                ),
                ("local", models.CharField(max_length=200, verbose_name="Local")),
                ("descricao", models.TextField(verbose_name="Descrição e Detalhes")),
                (
                    "libras_disponivel",
                    models.BooleanField(
                        default=True, verbose_name="Intérpretes de LIBRAS confirmados"
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="eventos/",
                        verbose_name="Imagem / Banner",
                    ),
                ),
                (
                    "imagem_url",
                    models.URLField(
                        blank=True, verbose_name="URL da Imagem (opcional)"
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(
                        default=False, verbose_name="Destaque na Página Inicial"
                    ),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Publicado")),
            ],
            options={
                "verbose_name": "Evento",
                "verbose_name_plural": "Eventos",
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="MembroDiretoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, verbose_name="Nome Completo"),
                ),
                ("cargo", models.CharField(max_length=100, verbose_name="Cargo")),
                (
                    "gestao",
                    models.CharField(
                        default="2024-2028",
                        max_length=50,
                        verbose_name="Gestão / Quadriênio",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Ordem de Exibição"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="diretoria/",
                        verbose_name="Foto Oficial",
                    ),
                ),
                (
                    "foto_url",
                    models.URLField(blank=True, verbose_name="URL da Foto (opcional)"),
                ),
                (
                    "bio",
                    models.TextField(blank=True, verbose_name="Biografia / Resumo"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail institucional"
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="WhatsApp / Contato"
                    ),
                ),
            ],
            options={
                "verbose_name": "Membro da Diretoria",
                "verbose_name_plural": "Diretoria Executiva",
                "ordering": ["ordem", "nome"],
            },
        ),
        migrations.CreateModel(
            name="MensagemContato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150, verbose_name="Nome")),
                ("email", models.EmailField(max_length=254, verbose_name="E-mail")),
                (
                    "telefone",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Telefone / WhatsApp"
                    ),
                ),
                ("assunto", models.CharField(max_length=150, verbose_name="Assunto")),
                ("mensagem", models.TextField(verbose_name="Mensagem")),
                (
                    "video_libras_url",
                    models.URLField(
                        blank=True, verbose_name="Link do Vídeo em LIBRAS (opcional)"
                    ),
                ),
                (
                    "data_envio",
                    models.DateTimeField(auto_now_add=True, verbose_name="Enviado em"),
                ),
                (
                    "respondido",
                    models.BooleanField(default=False, verbose_name="Respondido"),
                ),
            ],
            options={
                "verbose_name": "Mensagem de Contato",
                "verbose_name_plural": "Mensagens de Contato",
                "ordering": ["-data_envio"],
            },
        ),
        migrations.CreateModel(
            name="ModalidadeEsportiva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Modalidade"),
                ),
                (
                    "categoria",
                    models.CharField(
                        default="Masculino e Feminino",
                        max_length=50,
                        verbose_name="Categoria",
                    ),
                ),
                (
                    "icone",
                    models.CharField(
                        default="fa-futbol",
                        max_length=50,
                        verbose_name="Ícone FontAwesome",
                    ),
                ),
                (
                    "dias_treino",
                    models.CharField(
                        max_length=150, verbose_name="Dias e Horários de Treino"
                    ),
                ),
                (
                    "local_treino",
                    models.CharField(max_length=200, verbose_name="Local de Treino"),
                ),
                (
                    "responsavel",
                    models.CharField(
                        max_length=120, verbose_name="Responsável Técnico / Coordenador"
                    ),
                ),
                ("descricao", models.TextField(verbose_name="Descrição da Modalidade")),
                (
                    "ativa",
                    models.BooleanField(default=True, verbose_name="Ativa na ASSGA"),
                ),
            ],
            options={
                "verbose_name": "Modalidade Esportiva",
                "verbose_name_plural": "Modalidades Esportivas",
            },
        ),
        migrations.CreateModel(
            name="Noticia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=250, verbose_name="Título da Notícia"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, unique=True, verbose_name="Slug / URL"
                    ),
                ),
                ("resumo", models.TextField(verbose_name="Resumo")),
                (
                    "conteudo",
                    models.TextField(
                        verbose_name="Conteúdo Completo (HTML ou Markdown)"
                    ),
                ),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="noticias/",
                        verbose_name="Imagem da Capa",
                    ),
                ),
                (
                    "imagem_url",
                    models.URLField(
                        blank=True, verbose_name="URL da Imagem (opcional)"
                    ),
                ),
                (
                    "data_publicacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Publicação"
                    ),
                ),
                (
                    "destaque",
                    models.BooleanField(default=False, verbose_name="Destaque"),
                ),
            ],
            options={
                "verbose_name": "Notícia",
                "verbose_name_plural": "Notícias e Comunicados",
                "ordering": ["-data_publicacao"],
            },
        ),
        migrations.CreateModel(
            name="ArtigoEstatuto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.PositiveIntegerField(verbose_name="Número do Artigo"),
                ),
                ("texto", models.TextField(verbose_name="Texto do Artigo")),
                (
                    "paragrafo_unico",
                    models.TextField(
                        blank=True, verbose_name="Parágrafo Único / Incisos"
                    ),
                ),
                (
                    "capitulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artigos",
                        to="core.capituloestatuto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Artigo do Estatuto",
                "verbose_name_plural": "Artigos do Estatuto",
                "ordering": ["capitulo__ordem", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Carteirinha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_autenticacao",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=64,
                        unique=True,
                        verbose_name="Código de Autenticação",
                    ),
                ),
                ("via", models.PositiveIntegerField(default=1, verbose_name="Via")),
                (
                    "data_emissao",
                    models.DateField(auto_now_add=True, verbose_name="Data de Emissão"),
                ),
                ("data_validade", models.DateField(verbose_name="Data de Validade")),
                ("ativa", models.BooleanField(default=True, verbose_name="Ativa")),
                (
                    "associado",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carteirinha",
                        to="core.associado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Carteirinha",
                "verbose_name_plural": "Carteirinhas",
            },
        ),
        migrations.CreateModel(
            name="Mensalidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes_referencia",
                    models.PositiveSmallIntegerField(verbose_name="Mês de Referência"),
                ),
                (
                    "ano_referencia",
                    models.PositiveIntegerField(verbose_name="Ano de Referência"),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        default=25.0,
                        max_digits=8,
                        verbose_name="Valor (R$)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pago", "Pago"),
                            ("Pendente", "Pendente"),
                            ("Atrasado", "Atrasado"),
                            ("Isento", "Isento"),
                        ],
                        default="Pendente",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("PIX", "PIX"),
                            ("Dinheiro", "Dinheiro"),
                            ("Transferência", "Transferência"),
                            ("Cartão", "Cartão de Crédito/Débito"),
                        ],
                        default="PIX",
                        max_length=30,
                        verbose_name="Método de Pagamento",
                    ),
                ),
                (
                    "data_pagamento",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Data do Pagamento"
                    ),
                ),
                (
                    "comprovante",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="comprovantes/",
                        verbose_name="Comprovante",
                    ),
                ),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Registrado em"
                    ),
                ),
                (
                    "associado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mensalidades",
                        to="core.associado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mensalidade",
                "verbose_name_plural": "Mensalidades",
                "ordering": ["-ano_referencia", "-mes_referencia"],
                "unique_together": {("associado", "mes_referencia", "ano_referencia")},
            },
        ),
    ]
